### ISSUE TITLE
Operating Systems and app worth mentioning 

### ISSUE THREAD

**Issue by NotMainstream** [cqcore/Privacy-Infosec-Tools-Resources#1]
Hello,
Thanks for the list. I would like to propose if you think they are up for the job:
Operating Systems:
-GrapheneOS ( Best security and annonimity oriented Android version out there )
-SecureBlue Linux (it's a rebase of imutable Fedora Silverblue that is hardened that is much more secure than the OSs mentioned in the list.)

Android app:
-RethinkDNS & Firewall ( which is the most complex firewall for mobile with incredible features like multiple VPN profiles run in parallel for different selections of apps, hostnames banning for individual apps to kill telemetry for individual apps, DNS lists, best stats I have ever seen, packet capture and many other features

All of them are free open source projects.
Thanks.

**Comment by The-Osint-Toolbox** [comment]
Hi NotMainstream, I am familiar with Graphene which I have added. I am not familar with the others, but I will do some reearch and assess them. Thank you for getting in touch.

**Comment by NotMainstream** [comment]
Glad to help !
